### ISSUE TITLE
Could you please tell me the exact version of Opencv and python that you used?

### ISSUE THREAD

**Issue by iluvrachel** [dcastro9/smart_mirror_project#1]
i can't run the code on my environment

**Comment by dcastro9** [comment]
This was 4 years ago -- honestly don't remember but guessing from 4 years ago:
OpenCV 2.4.X (likely anything works but something like 2.4.8 is best timeline-wise)
Python 2.7

**Comment by iluvrachel** [comment]
appreciate it!
